Vagrant.configure("2") do |configLS|

  configLS.vm.provision "file", source: File.expand_path("../id_rsa.pub", __FILE__), destination: "~/.ssh/authorized_keys"
  configLS.ssh.insert_key = false
  configLS.ssh.private_key_path = [File.expand_path("../id_rsa", __FILE__), "~/.vagrant.d/insecure_private_key"]

  configLS.vm.box = "bento/centos-7.2"

  configLS.vm.define "SAM-node"
  configLS.vm.hostname = "samnode"
  configLS.vm.network "private_network", ip:"192.168.77.30"
  configLS.vm.box_check_update = false
  configLS.vm.provider "virtualbox" do |v|
          v.memory = 4096
          v.cpus = 1
        end

  configLS.vm.provision "shell", privileged: true, inline: <<-SHELL
    yum install -y epel-release
    yum update -y
    yum install -y python python-pip python-devel awscli PyYAML aws-sam-cli yum-utils device-mapper-persistent-data lvm2
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    yum-config-manager --enable docker-ce-edge
    yum-config-manager --enable docker-ce-test
    yum install -y docker-ce
    systemctl enable docker
    systemctl start docker
  SHELL

  for port in 4567..4582 do
    configLS.vm.network "forwarded_port", guest: port, host: port
  end
end
